README.md, src/build_cfg.c, src/fail.c, src/free.c, src/jou_compiler.h, src/main.c, src/print.c, src/simplify_cfg.c, tests/runtests.sh, tests/should_succeed/compiler_cli.jou, tests/should_succeed/unreachable_after_return.jou
=> Add unreachable code warning

README.md, src/build_cfg.c, src/codegen.c, src/free.c, src/jou_compiler.h, src/print.c, src/simplify_cfg.c, tests/should_succeed/if.jou, tests/should_succeed/return_void.jou, tests/should_succeed/unreachable_after_return.jou, tests/should_succeed/unreachable_warning.jou, tests/should_succeed/unused_argument.jou
=> Add more CFG analysing

src/simplify_cfg.c, tests/should_succeed/unreachable_warning.jou
It was a mess that just happened to work for test cases. It's still a mess, but at least I know why it works now.
Also, fixes #18
=> Rewrite the code that shows unreachable warnings

src/jou_compiler.h, src/print.c, src/simplify_cfg.c, tests/should_succeed/return_void.jou, tests/should_succeed/unreachable_warning.jou
=> Get rid of analyzable boolean

src/build_cfg.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, tests/other_errors/var_already_exists.jou, tests/should_succeed/implicit_conversions.jou, tests/wrong_type/assign_with_type.jou
=> 'x: int' improvements

src/build_cfg.c, src/codegen.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/simplify_cfg.c, src/types.c
No new functionality, but this makes constants easier to reason about (although it is a bit more code)
=> Refactor Constant

src/parse.c, tests/should_succeed/pointer.jou
=> Allow more complicated indexing expressions

src/build_cfg.c, tests/should_succeed/pointer.jou
But in general, cannot do ptr+int or ptr-int yet.
=> Add ++ and -- operators for pointers

src/main.c, src/print.c
=> Refactor AST printing

src/build_cfg.c, src/codegen.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/tokenize.c, src/types.c, tests/should_succeed/as.jou, tests/should_succeed/implicit_conversions.jou
=> Add explicit casts ("obj as type" syntax)

src/jou_compiler.h, src/print.c, src/tokenize.c, tests/should_succeed/divide.jou, tests/syntax_error/0b2.jou, tests/syntax_error/2bad.jou, tests/syntax_error/bin.jou, tests/syntax_error/hex.jou, tests/syntax_error/unnecessary_zero.jou
Also fixed tokenizing to support 64 bit values.
=> add hex and bin numbers

src/build_cfg.c, src/typecheck.c, tests/other_errors/address_of_minusminus.jou, tests/other_errors/double_plusplus.jou, tests/other_errors/dumb_assignment.jou, tests/other_errors/immediate_member_assign.jou, tests/syntax_error/bad_addressof.jou, tests/wrong_type/pointer_assignment.jou, tests/wrong_type/struct_member_assign.jou, tests/wrong_type/var_assignment.jou
Fixes #60
Improves many existing error messages
=> Improve address-of related error handling

src/build_cfg.c, tests/should_succeed/struct.jou
=> Fix accessing fields of non-"addressable" struct objects

src/free.c, src/jou_compiler.h, src/main.c, src/tokenize.c, tests/404/file.jou
=> Improve error message for importing non-existent file

src/main.c, tests/should_succeed/compiler_cli.jou, tests/should_succeed/foo/bar.jou, tests/should_succeed/local_import.jou, tests/syntax_error/import_missing_dot.jou
=> Find stdlib, even if not in current working dir

src/build_cfg.c, src/free.c, src/jou_compiler.h, src/main.c, src/parse.c, src/print.c, src/typecheck.c, tests/404/import_symbol.jou, tests/404/import_wrong_func.jou, tests/should_succeed/compiler_cli.jou, tests/syntax_error/missing_import_keyword.jou
=> Import improvements

src/build_cfg.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/typecheck.c, tests/should_succeed/add.jou, tests/wrong_type/neg.jou
=> prefix - operator

.github/workflows/check.yml, .github/workflows/linux.yml, .github/workflows/release.yml, .github/workflows/windows.yml, Makefile
If I get this to work, it will make using Jou on Windows very easy:
1. Download a zip file
2. Extract the zip file
3. Add the extracted zip file to PATH
4. in command prompt: `jou hello.jou`
=> Cross compile for Windows in GitHub Actions

.github/workflows/release.yml, .github/workflows/windows.yml
Created in #106, but couldn't test on #106.
=> Fix release workflow

.github/workflows/linux.yml
=> Update `actions/checkout` in `linux.yml` to v3

.github/workflows/release.yml
=> Run release workflow every 3h

.github/workflows/windows.yml, jou.cbp
=> Add github actions check to check files in codeblocks project

update.ps1
=> jou --update: Avoid erasing the installation directory on Windows

src/build_cfg.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/tokenize.c, src/typecheck.c, tests/other_errors/dumb_assignment_with_plusequals.jou, tests/should_succeed/add_sub_mul_div_mod.jou, tests/wrong_type/inplace_add_doesnt_go_back.jou
=> in-place operations

src/codegen.c, src/free.c, src/jou_compiler.h, src/main.c, src/parse.c, src/print.c, src/typecheck.c, tests/404/import_symbol.jou, tests/404/import_symbol_multiline.jou, tests/other_errors/double_definition.jou, tests/other_errors/import_def.jou, tests/other_errors/struct_already_exists.jou, tests/should_succeed/foo/bar.jou, tests/should_succeed/local_import.jou
=> Struct import

src/typecheck.c, tests/should_succeed/file.jou, tests/wrong_type/array_vararg.jou
=> Add an error for trying to pass an array as vararg

src/run.c
=> fix quoting on windows

.github/workflows/windows.yml, update.ps1
Added:
- Jou license
- Jou documentation
- Jou examples
- MinGW licenses
=> Include more files in the releases

.github/workflows/windows.yml, src/run.c
=> Run tests in a directory that contains a space

.github/workflows/windows.yml, src/build_cfg.c, src/codegen.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/run.c, src/simplify_cfg.c, src/tokenize.c, src/typecheck.c, stdlib/io.jou, tests/404/local_var.jou, tests/404/local_var_addressof.jou, tests/404/var.jou, tests/404/var_addressof.jou, tests/other_errors/var_shadow.jou, tests/should_succeed/global.jou, tests/should_succeed/global_bug.jou, tests/should_succeed/printf.jou, tests/syntax_error/arg_default.jou, tests/syntax_error/declare_global_with_value.jou, tests/syntax_error/struct_default.jou
=> Global variables

.github/workflows/linux.yml, .github/workflows/windows.yml, CONTRIBUTING.md, runtests.sh
=> runtests.sh: Add verbose mode

.github/workflows/windows.yml
=> Convert to CRLF

src/codegen.c, src/run.c, src/tokenize.c, src/typecheck.c, tests/should_succeed/add_sub_mul_div_mod.jou, tests/should_succeed/implicit_conversions.jou, tests/syntax_error/float.jou, tests/wrong_type/float_and_double.jou
=> Fix 12.34f syntax

src/typecheck.c, tests/should_succeed/implicit_conversions.jou
=> Add implicit cast from float to double.

src/codegen.c, src/typecheck.c, tests/should_succeed/as.jou
=> Fix explicit casts involving floats/doubles

src/codegen.c, src/jou_compiler.h, src/print.c, src/typecheck.c, src/types.c
Maybe slightly cleaner this way. Not a huge difference.
=> Combine TYPE_FLOAT and TYPE_DOUBLE into TYPE_FLOATING_POINT

src/codegen.c, src/free.c, src/jou_compiler.h, src/main.c, src/parse.c, src/typecheck.c, tests/other_errors/imported_error.jou, tests/should_succeed/compiler_cli.jou, tests/should_succeed/plusplus_minusminus.jou, tests/should_succeed/unused_import.jou
=> Add warnings for unused imports

examples/x11_window.jou, runtests.sh, src/jou_compiler.h, src/main.c, src/run.c, tests/should_succeed/compiler_cli.jou
A bit annoying to use, but fixes #214 for now. Hopefully I will eventually create an actual package manager.
=> Add a --linker-flags argument

src/typecheck.c, tests/wrong_type/assign_void.jou
Fixes #223 
First commit created on my phone lol
=> Use more typecheck_expression_not_void

.github/workflows/linux.yml, .github/workflows/windows.yml, jou.cbp, runtests.sh, src/codegen.c, src/jou_compiler.h, src/main.c, src/run.c, src/target.c, stdlib/mem.jou, tests/should_succeed/sizeof.jou
Fixes #224 
Marking as a draft for now, because I haven't found a fix yet, although I added a test case.
=> Fix the weird sizeof bug

.github/workflows/linux.yml, .github/workflows/release.yml
I noticed that `windows.yml` was indented differently from the other two. I liked how it was indented, so I indented the other two in the same style.
Not really critical, but makes copy/pasting between the files easier.
=> Make indentation of yaml files consistent

src/tokenize.c
=> Simplify how newline tokens work

doc/syntax-spec.md, self_hosted/tokenizer.jou, src/tokenize.c
=> Syntax spec: tokenizing

src/typecheck.c
=> Simplify handle_struct_fields() slightly

self_hosted/errors_and_warnings.jou, self_hosted/tokenizer.jou
This code was written before Jou had methods.
=> Use methods in the self-hosted compiler

self_hosted/tokenizer.jou, self_hosted/tokenizes_wrong.txt, src/build_cfg.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/typecheck.c, tests/should_succeed/array.jou, tests/syntax_error/bad_array.jou, tests/wrong_type/array_mixed_types.jou, tests/wrong_type/array_mixed_types_ptr.jou
=> add nicer array syntax

.github/workflows/linux.yml
=> github actions: Avoid running valgrind when it is unnecessary

src/parse.c, tests/syntax_error/arg_default.jou
=> Small parser tweaks

src/print.c
Extracted from #271. These aren't tested because it would be quite tedious.
=> Fix various AST printing bugs

doc/syntax-spec.md, self_hosted/ast.jou, self_hosted/parses_wrong.txt, self_hosted/token.jou, self_hosted/tokenizer.jou, src/parse.c, src/tokenize.c, src/typecheck.c, tests/other_errors/method_on_ptr_called_on_class.jou, tests/should_succeed/imported/bar.jou, tests/should_succeed/linked_list.jou, tests/should_succeed/method.jou, tests/syntax_error/self_as_varname.jou, tests/syntax_error/self_outside_class.jou
=> Nicer self syntax

self_hosted/find_jou_installation.jou
=> Fix uninitialized memory bug in self_hosted/find_jou_installation.jou

doc/syntax-spec.md, self_hosted/tokenizer.jou, src/tokenize.c, tests/should_succeed/array.jou, tests/should_succeed/string_syntax.jou, tests/syntax_error/string_bad_hex.jou, tests/syntax_error/string_zero_byte_hex.jou
=> Add \x escapes, delete dumb \1,\2,... escapes

src/typecheck.c, tests/should_succeed/as.jou
=> Allow casting bool to int

self_hosted/main.jou, self_hosted/parser.jou, self_hosted/typecheck.jou, src/typecheck.c, tests/should_succeed/linked_list.jou
=> Support the "malloc idiom"

.github/workflows/windows.yml, self_hosted/main.jou, src/run.c
=> Let's try gcc for linking on Windows

Makefile.windows, activate, windows_setup.sh
I haven't had access to a Windows system for the past few days, so the Windows build wasn't great. I now have Windows running in a virtual machine, but it's annoyingly slow and almost unusable, so I haven't tested this PR with it (yet).
Without access to a Windows computer, the best I can do is to fix any problems that littlewhitecloud points out. Fixes #300
=> Fixes to windows build things

compare_compilers.sh
I finally have access to a reasonably working Windows system. I ran all scripts (`windows_setup.sh`, `runtests.sh`, `compare_compilers.sh`) on Windows. I discovered and fixed a couple problems in `compare_compilers.sh` and the other two worked for me.
=> Windows fixes to compare_compilers.sh

self_hosted/ast.jou
the old order of classes didn't make any sense to me. They are now ordered roughly so that the "biggest" things (e.g. AstFile) are last, and the "smallest" things (AstType, AstExpression) are first.
=> Rearrange self_hosted/ast.jou

.github/workflows/release.yml, CONTRIBUTING.md
Right now it makes a release for almost every PR which seems unnecessary.
=> Run release once per day

self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, self_hosted/tokenizer.jou, self_hosted/tokenizes_wrong.txt, src/tokenize.c, tests/syntax_error/c_and.jou, tests/syntax_error/c_not.jou, tests/syntax_error/c_or.jou, tests/syntax_error/triple_not_equals.jou
=> Handle better using the wrong operator

compare_compilers.sh, self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, self_hosted/tokenizer.jou, self_hosted/tokenizes_wrong.txt, src/tokenize.c, tests/syntax_error/tab.jou
=> Improve handling bad bytes in source files

self_hosted/ast.jou, self_hosted/create_llvm_ir.jou, self_hosted/parser.jou, self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, self_hosted/typecheck.jou, src/parse.c, src/print.c, tests/other_errors/global_value_not_yet_implemented.jou
All test files now parse correctly.
=> Finish self-hosted parser

.editorconfig, .github/workflows/linux.yml, .github/workflows/windows.yml, CONTRIBUTING.md, self_hosted/create_llvm_ir.jou, self_hosted/main.jou, self_hosted/tokenizer.jou, self_hosted/typecheck.jou, src/jou_compiler.h, src/parse.c, src/tokenize.c, src/types.c, src/util.h, tests/should_succeed/add_sub_mul_div_mod.jou
=> .editorconfig

self_hosted/ast.jou, src/print.c
=> Improve self printing

self_hosted/ast.jou, self_hosted/create_llvm_ir.jou, self_hosted/parser.jou, self_hosted/target.jou, self_hosted/token.jou, self_hosted/typecheck.jou, self_hosted/types.jou, src/build_cfg.c, src/codegen.c, src/free.c, src/jou_compiler.h, src/print.c, src/typecheck.c, tests/other_errors/string_doesnt_fit_to_array.jou, tests/should_succeed/string_initialize_byte_array.jou
=> Convert string constants to arrays

self_hosted/parser.jou, self_hosted/runs_wrong.txt, src/parse.c
=> Refactor parser to a class

self_hosted/parser.jou, self_hosted/runs_wrong.txt, self_hosted/typecheck.jou, src/parse.c, src/typecheck.c, tests/other_errors/self_assign_in_function.jou, tests/other_errors/self_assign_in_method.jou, tests/other_errors/self_declare_local_var_in_function.jou, tests/other_errors/self_declare_local_var_in_method.jou, tests/other_errors/self_use_in_function.jou
=> Improve self errors

self_hosted/ast.jou, self_hosted/create_llvm_ir.jou, self_hosted/main.jou, self_hosted/parser.jou, self_hosted/typecheck.jou, src/build_cfg.c, src/free.c, src/jou_compiler.h, src/main.c, src/parse.c, src/print.c, src/typecheck.c, tests/syntax_error/bad_toplevel_declaration.jou, tests/syntax_error/bad_toplevel_statement.jou, tests/syntax_error/first_line_indent.jou
The idea is to refactor things so that a file contains `AstStatement`s directly. This way I can e.g. parse `if` statements that are not inside a function, needed for #385.
=> Refactor AST

stdlib/ascii.jou
Fixes #403 
No matter what I do, I can't get valgrind to detect this automagically for some reason, so we'll just rely on manual code review to spot these...
=> Let's just use memmove

self_hosted/typecheck.jou
For some reason the same thing was repeated twice.
=> Remove duplicated code

src/output.c
=> .gitinore in jou_compiled

src/simplify_cfg.c, tests/should_succeed/unused_variable.jou
=> Silence unused var warning for variables starting with _

self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, src/build_cfg.c, src/parse.c, src/print.c, src/typecheck.c, src/types.c, tests/should_succeed/method_by_value.jou, tests/wrong_type/self_annotation.jou
=> Methods that take self by value

examples/aoc2023/day24/bigint.jou, examples/aoc2023/day24/part1.jou, examples/aoc2023/day24/part2.jou
This is what I originally created them for.
=> Use self-by-value methods in AoC solutions

self_hosted/evaluate.jou, src/evaluate.c, tests/should_succeed/compile_time_if.jou
=> Support and/or/not operators in compile-time checks

doctest.sh
=> doctest: Do not pass newline to "base64 -d"

doctest.sh
I haven't developed Jou in a while. Let's see if CI is still green.
=> doctest.sh: Delete unused slice function

README.md, doc/ai-thoughts.md
Tl;dr: I wrote some Jou code with an LLM that didn't know about Jou, asked what it thinks about Jou, and got a really nice response.
=> Document my AI+Jou experiment

self_hosted/ast.jou, self_hosted/parser.jou, self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, src/print.c
This PR finishes `self_hosted/parser.jou` so that the self-hosted compiler can parse any file exactly like the compiler written in C.
=> Complete the parser of self-hosted compiler

self_hosted/paths.jou
Pull request #526 fixed this in the Jou compiler written in C, but not in the Jou compiler written in Jou (self-hosted compiler).
=> Port path finding fix to self-hosted

compiler/main.jou, compiler/paths.jou
This is important, because anyone trying to figure out how the compiler works will probably start from `main.jou` (or documentation).
Part of #565.
=> Refactor compiler/main.jou

compiler/ast.jou, compiler/build_cfg.jou, compiler/parser.jou, compiler/typecheck.jou
=> Clean up compiler/ast.jou

compiler/codegen.jou
=> Refactor compiler/codegen.jou to use a class

compiler/update.jou
Already pretty clean, not much to do here.
Part of #565
=> Clean up compiler/update.jou

compiler/build_cf_graph.jou, compiler/cf_graph.jou, compiler/codegen.jou, compiler/main.jou, compiler/structs.jou, compiler/typecheck.jou, compiler/types.jou
=> Clean up compiler/types.jou

compiler/typecheck/step3_function_and_method_bodies.jou, tests/wrong_type/voidptr_increment.jou, tests/wrong_type/voidptr_index.jou
=> Add compiler error for incrementing/decrementing void pointers

compiler/build_cf_graph.jou
This is a big file. The diff is basically unreadable, but it basically puts everything into one big class and that's it.
Part of #565
=> Refactor compiler/build_cf_graph.jou to use a class

compiler/build_cf_graph.jou, compiler/cf_graph.jou, compiler/codegen.jou, compiler/command_line_args.jou, compiler/constants.jou, compiler/main.jou, compiler/output.jou, compiler/paths.jou
=> Move content of compiler/structs.jou into other files

compiler/ast.jou, compiler/cf_graph.jou, compiler/codegen.jou, compiler/typecheck/common.jou, compiler/typecheck/step1_create_types.jou, compiler/typecheck/step2_populate_types.jou, compiler/typecheck/step3_function_and_method_bodies.jou, compiler/types.jou
Small tweaks, didn't want to make separate PR for each.
Part of #565
=> Misc refactoring to self-hosted compiler

doc/enums.md
=> Document enums

compiler/ast.jou, compiler/build_cf_graph.jou, compiler/cf_graph.jou, compiler/codegen.jou, compiler/constants.jou, compiler/evaluate.jou, compiler/main.jou, compiler/parser.jou, compiler/target.jou, compiler/token.jou, compiler/tokenizer.jou, compiler/typecheck/common.jou, compiler/typecheck/step1_create_types.jou, compiler/typecheck/step2_populate_types.jou, compiler/typecheck/step3_function_and_method_bodies.jou, compiler/types.jou, examples/aoc2023/day20/part1.jou, examples/aoc2023/day20/part2.jou, examples/aoc2024/day14/part1.jou, examples/aoc2024/day24/part1.jou, examples/aoc2024/day24/part2.jou
=> Use . enum syntax instead of :: in all Jou files

.github/workflows/linux.yml, CONTRIBUTING.md, README.md, check-markdown-links.py
fix #602 (I hope my modification works, I am not good at adding test in the .yml files)
=> Add markdown link checker

check-markdown-links.py, doc/imports.md
=> Document imports

compiler/ast.jou, compiler/build_cf_graph.jou, compiler/cf_graph.jou, compiler/codegen.jou, compiler/evaluate.jou, compiler/main.jou, compiler/typecheck/common.jou, compiler/typecheck/step3_function_and_method_bodies.jou, compiler/types.jou
=> Use even more match statements in the compiler

compiler/cf_graph.jou
=> Fix memory leak in cf_graph.jou

compiler/evaluate.jou, tests/404/compile_time_constant.jou
=> Fix no error for unknown compile time constant

bootstrap_compiler/free.c, bootstrap_compiler/typecheck.c, compiler/typecheck/step2_populate_types.jou
=> Fix memory leaks

bootstrap_compiler/tokenize.c, compiler/tokenizer.jou, tests/should_succeed/underscore_number.jou, tests/syntax_error/number_underscore_prefix.jou, tests/syntax_error/number_underscore_prefix_hex.jou, tests/syntax_error/number_underscore_suffix.jou, tests/syntax_error/number_underscore_suffix_hex.jou
=> Allow underscores in number literals

bootstrap_compiler/main.c
=> Fix C compiler warning in bootstrap compiler

bootstrap_compiler/jou_compiler.h, bootstrap_compiler/typecheck.c, compiler/main.jou, compiler/typecheck/common.jou, compiler/typecheck/step1_create_types.jou, compiler/typecheck/step2_populate_types.jou, compiler/typecheck/step3_function_and_method_bodies.jou
=> Misc code cleanups

compiler/ast.jou, compiler/main.jou, compiler/paths.jou, compiler/typecheck/step2_populate_types.jou, examples/aoc2023/day25/part1.jou, examples/aoc2024/day08/part2.jou, tests/other_errors/missing_main_function.jou, tests/should_succeed/unused_function.jou
=> Add unused function warning

compiler/parser.jou, tests/should_succeed/not_warning.jou
=> Add warnings for combining not with == and !=

doc/types.md, tests/should_succeed/sizeof.jou
=> Document types

compiler/parser.jou, tests/should_succeed/pass.jou, tests/should_succeed/unnecessary_parens_warning.jou
=> Add unnecessary parentheses warning

.github/workflows/windows.yml
=> GitHub Actions: include .a files in Windows bootstrap artifact

.github/workflows/valgrind.yml
Noticed when looking at CI output.
=> github actions: Delete unnecessary steps in valgrind.yml

doctest.sh, runtests.sh
=> Attempt to detect gdiff only on NetBSD

windows_setup.sh
=> Add offline mode to windows_setup.sh

compiler/typecheck/step3_function_and_method_bodies.jou, tests/wrong_type/method_arg.jou
=> Improve error message for wrong argument of method

compiler/builders/ast_to_builder.jou, compiler/typecheck/step3_function_and_method_bodies.jou, tests/should_succeed/plusplus_minusminus.jou
=> Add ++ and -- for float/double

compiler/typecheck/step3_function_and_method_bodies.jou, tests/should_succeed/match.jou, tests/wrong_type/match_bool.jou, tests/wrong_type/match_class.jou, tests/wrong_type/match_float.jou, tests/wrong_type/match_not_enum.jou, tests/wrong_type/match_string_without_strcmp.jou
=> Allow using match statement with integers

bootstrap.sh, compiler/tokenizer.jou
=> Compiler code cleanup: delete bytecmp function

stdlib/str.jou
Makes it consistent with the comment above.
=> Rename strcspn parameter

.github/workflows/checks.yml, Makefile
=> Do not use an action for editorconfig-checker

.github/workflows/netbsd.yml
=> Update todo comment in netbsd.yml

compiler/uvg_analyze.jou
=> Fix a memory leak in uvg_analyze.jou

compiler/evaluate.jou, compiler/uvg_analyze.jou, tests/should_succeed/compile_time_if.jou, tests/wrong_type/elif.jou
=> Support True and False in compile-time if statements

compiler/parser.jou, tests/should_succeed/loops.jou
=> Show warning if nested loops use the same variable

bootstrap.sh, compiler/ast.jou, compiler/builders/uvg_builder.jou, compiler/constants.jou, compiler/llvm.jou, compiler/main.jou, compiler/parser.jou, compiler/token.jou, compiler/typecheck/common.jou, compiler/typecheck/step1_create_types.jou, compiler/types.jou, compiler/uvg.jou, examples/aoc2024/day20/part1.jou, examples/aoc2024/day20/part2.jou, tests/other_errors/import_private_enum.jou, tests/other_errors/import_private_function.jou, tests/other_errors/imported/privates.jou, tests/should_succeed/imported/bar.jou, tests/should_succeed/unused_enum.jou
=> Make enums private if not decorated with `@public`

compiler/ast.jou, compiler/builders/ast_to_builder.jou, compiler/builders/llvm_builder.jou, compiler/builders/uvg_builder.jou, compiler/main.jou, tests/other_errors/import_file_with_main.jou, tests/should_succeed/import_file_with_main.jou, tests/should_succeed/public_hello_printer.jou
Fixes #742
This was surprisingly easy to implement.
=> Allow importing files with main function

.github/workflows/release.yml
Don't know how I missed this when configuring GitHub Actions.
=> Do not create a release every night on forks

compiler/uvg_analyze.jou, tests/other_errors/missing_return.jou
The test for #3 was not enabled for some reason.
=> Tweak missing return statement error message, add back test

bootstrap.sh, compiler/ast.jou, compiler/builders/ast_to_builder.jou, compiler/builders/either_builder.jou, compiler/builders/llvm_builder.jou, compiler/builders/uvg_builder.jou, compiler/constants.jou, compiler/llvm.jou, compiler/parser.jou, compiler/paths.jou, compiler/tokenizer.jou, compiler/typecheck/common.jou, compiler/typecheck/step2_populate_types.jou, compiler/typecheck/step3_function_and_method_bodies.jou, compiler/types.jou, compiler/utils.jou, compiler/uvg_analyze.jou, stdlib/io.jou, tests/should_succeed/end_of_file_spaces.jou
This PR makes the compiler more readable, but doesn't affect using it in any way.
=> Compiler code cleanups

compiler/main.jou, compiler/parser.jou, compiler/paths.jou, compiler/run.jou, compiler/token.jou, compiler/tokenizer.jou, compiler/typecheck/step3_function_and_method_bodies.jou, stdlib/str.jou, tests/should_succeed/strlibtest.jou
This function is like `sprintf()`, except that it allocates a new string of the right size with `malloc()`. It is not in the C standard, but all 4 supported platforms seem to have it.
Thank you @taahol for letting me know that this function exists :)
=> Declare the `asprintf()` function

.github/workflows/netbsd.yml, Makefile.posix, README.md, bootstrap.sh
A PR for changes done by @taahol in #774. Depends on #774, and I will merge it first.
=> Fix NetBSD support

compiler/typecheck/step3_function_and_method_bodies.jou, tests/should_succeed/array_of_nulls.jou, tests/wrong_type/array_with_hint.jou
=> Respect type hints when type-checking array items

compiler/builders/ast_to_builder.jou, tests/should_succeed/noreturn_function.jou, tests/should_succeed/noreturn_method.jou, tests/should_succeed/unreachable_warning.jou
=> Fix bug when using `-> noreturn` for methods

compiler/run.jou
=> Fix unused import warning when compiling the compiler

tests/should_succeed/list_test.jou
I am getting a segfault in #816 and I thought tests might help reproduce it. Probably should have added tests when I created `List`...
=> Add tests for List

examples/aoc2023/day05/part2.jou, examples/aoc2023/day08/part2.jou, examples/aoc2023/day12/part1.jou, examples/aoc2023/day12/part2.jou, examples/aoc2023/day14/part2.jou, examples/aoc2023/day16/part1.jou, examples/aoc2023/day16/part2.jou, examples/aoc2023/day18/part1.jou, examples/aoc2023/day18/part2.jou, examples/aoc2023/day19/part1.jou, examples/aoc2023/day19/part2.jou, examples/aoc2023/day20/part1.jou, examples/aoc2023/day20/part2.jou, examples/aoc2023/day23/part1.jou, examples/aoc2023/day23/part2.jou, examples/aoc2024/day11/part1.jou, examples/aoc2024/day17/part2.jou, examples/aoc2024/day20/part1.jou, examples/aoc2024/day20/part2.jou, examples/aoc2024/day21/part1.jou, stdlib/list.jou, tests/should_succeed/list_test.jou
The goal is not to rewrite everything possible with lists, but at least get rid of the `class List: ...` that I rewrote every time I needed a list.
=> Use lists in examples/aoc2023 and examples/aoc2024

compiler/tokenizer.jou, compiler/typecheck/step3_function_and_method_bodies.jou, examples/aoc2023/day12/part2.jou, examples/aoc2023/day16/part1.jou, examples/aoc2023/day16/part2.jou, examples/aoc2023/day18/part1.jou, examples/aoc2023/day19/part2.jou, examples/aoc2023/day23/part2.jou, stdlib/list.jou, tests/should_succeed/list_test.jou
Previously, `List.pop()` returned nothing due to limitations of the Jou language/compiler. With `@inline`, it is now possible to returned the value removed from the end of the list, just like Python does.
=> Return the removed element in `list.pop()`

compiler/builders/ast_to_builder.jou
=> Fix memory leak in compiler

doc/lists.md, examples/list_example.jou, stdlib/list.jou
=> Document lists

compiler/builders/ast_to_builder.jou, stdlib/list.jou, tests/should_succeed/generic_bugs.jou
=> More bug fixes for inline methods in generic classes

bootstrap.sh
=> Update the bootstrap compiler

compiler/main.jou
=> Allow interrupting the compiler while outputting .o file

compiler/ast.jou, compiler/builders/any_builder.jou, compiler/builders/ast_to_builder.jou, compiler/builders/hash_builder.jou, compiler/builders/llvm_builder.jou, compiler/builders/uvg_builder.jou, compiler/evaluate.jou, compiler/parser.jou, compiler/tokenizer.jou, compiler/typecheck/step3_function_and_method_bodies.jou, doc/compiler_internals/syntax-spec.md, examples/aoc2024/day17/part1.jou, examples/aoc2024/day17/part2.jou, examples/aoc2024/day22/part1.jou, examples/aoc2024/day22/part2.jou, tests/should_succeed/xor.jou, tests/wrong_type/inplace_xor.jou, tests/wrong_type/xor.jou
=> Add bitwise xor operator `^`

.github/workflows/checks.yml, compiler/command_line_args.jou, compiler/parser.jou, doc/inline.md, doc/tutorial.md, examples/aoc2023/day24/part2.jou, tests/should_succeed/unreachable_warning.jou
Actually, add codespell to CI so that it will complain if there are typos. (The title of this issue is written so that it shows up nicely in a changelog.)
=> Fix a few typos

check-markdown-links.py
=> Fix link checker

compiler/command_line_args.jou, compiler/errors_and_warnings.jou, compiler/main.jou, tests/should_succeed/compiler_cli.jou
=> Add --fail-on-warnings command line argument

README.md
I recently rewrote curses-klondike in Jou and cleaned up the code a lot.
=> README: Mention curses-klondike

compiler/ast.jou, compiler/builders/ast_to_builder.jou, compiler/parser.jou, compiler/typecheck/step3_function_and_method_bodies.jou, tests/other_errors/assign_to_ternary.jou, tests/should_succeed/ternary.jou, tests/syntax_error/ternary.jou, tests/wrong_type/ternary_condition.jou, tests/wrong_type/ternary_values.jou, tests/wrong_type/ternary_values_with_type_hint.jou
This now works:
```python
printf("Hello\n" if some_condition else "World\n")
```
Fixes #168
=> Add Python-style ternary operator

compiler/ast.jou
=> Fix memory leak

compiler/parser.jou, tests/syntax_error/self_not_first.jou
=> Add error if self is not the first argument

compiler/main.jou, compiler/paths.jou, compiler/run.jou, compiler/target.jou
This PR makes it much easier to see what the compiler does in different modes.
=> Refactor main.jou logic

examples/perlin_noise.jou, stdlib/io.jou
In #936, @olkku45 noticed that this function was missing.
=> Add fwrite() function to stdlib/io.jou

compiler/builders/hash_builder.jou
=> Recompile when type of local variable changes
