Akuli/jou

src/simplify_cfg.c, tests/should_succeed/unreachable_warning.jou
Fixes half of #15. The other half requires something to get rid of unnecessary address-ofs: if a variable named `flag` already exists, then `flag = False` becomes `*(&flag) = False` in the CFG, and `simplify_cfg` avoids touching variables whose address is used somewhere.
=> Better analyzing for values of booleans in simplify_cfg

src/jou_compiler.h, src/print.c, src/simplify_cfg.c, tests/should_succeed/undefined_value_warning.jou
~Fixes #26~ Adds warnings for code where you use or may use a variable before it is assigned.
=> Add a warning for attempting to use undefined variables

src/codegen.c, src/simplify_cfg.c, tests/other_errors/missing_return.jou, tests/should_succeed/infinite_loop_but_doesnt_return_void.jou
Fixes #3
In cases where the compiler doesn't know for sure that the return statement is missing, it only emits a warning, not an error.
=> Error for missing 'return' statement

src/build_cfg.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/simplify_cfg.c, tests/should_succeed/scanf.jou, tests/should_succeed/undefined_value_warning.jou
fixes #29
Also fixes a bug that generated a bunch of false-positive warnings when trying to use `sscanf()`
=> Add "x: int" syntax

src/build_cfg.c, src/free.c, src/jou_compiler.h, src/parse.c, src/print.c, src/simplify_cfg.c, tests/404/type.jou
Currently AST contains `Type`s, but that won't be good once we have structs: the AST building functions don't have any state apart from the stream of tokens (and I don't want to add any), so can't store a list of previously defined structs there.
This changes the AST to have types in a not-fully-compiled form so that the next compilation step (build_cfg) can handle struct names later.
Purely refactoring / adding boilerplate. No functionality changes.
=> Introduce AstType

.github/workflows/check.yml, Makefile, README.md
Found myself almost always pressing Ctrl+C to interupt valgrind
=> Separate valgrind from "make test"

README.md, src/build_cfg.c, src/codegen.c, src/free.c, src/jou_compiler.h, src/print.c, src/simplify_cfg.c, src/typecheck.c
Adds quite a lot more code, but will be needed for arrays: `foo[bar]` needs to take the address of the `foo` variable if it's an array, and otherwise it uses the *value* of the variable as the pointer.
=> Separate type checking and build_cfg

Makefile, src/build_cfg.c, src/parse.c, src/print.c, src/tokenize.c
It previously used gcc (actually, whatever the `cc` symlink points to). Using clang makes more sense because we depend on clang anyway.
=> Use clang to compile the compiler

src/main.c, tests/404/file.jou, tests/404/import_symbol.jou, tests/404/import_symbol_multiline.jou, tests/runtests.sh, tests/should_succeed/compiler_cli.jou
=> Do not rely on argv[0] to locate the executable

.github/workflows/linux.yml
Valgrinding is the slowest thing in the CI. This should speed up a bit.
=> Split valgrinding across two github actions jobs

.github/workflows/release.yml, .github/workflows/windows.yml, fuzzer.sh
CONTRIBUTING.md explains the main reason why this is a good idea. It could also make GitHub Actions faster, because currently it spends a lot of time uploading and downloading many small files that will now be zipped.
=> Move some logic from release.yml to windows.yml

src/run.c
Fixes the build on codeblocks (#170)
=> Include config.h only on linux

src/tokenize.c, tests/should_succeed/octalnuber.jou
Syntax:
octnumber = 0oxxxxx
Test:
```python
from "stdlib/io.jou" import printf
def main()-> int:
octnumber = 0o777 # Should be 511
printf("%d", octnumber)
return 0
```
=> oct number support

src/main.c, tests/should_succeed/imported/bar.jou, tests/should_succeed/local_import.jou
Previously, importing a struct wouldn't imports methods defined in the struct. Now that works.
=> Fix importing methods

compare_compilers.sh, self_hosted/parses_wrong.txt, self_hosted/token.jou, self_hosted/tokenizer.jou, self_hosted/tokenizes_wrong.txt, stdlib/str.jou, tests/should_succeed/int_literals.jou, tests/should_succeed/octalnuber.jou
- Parse ints and longs in all supported bases (binary, octal, decimal, hex)
- Support space-ignoring mode (see syntax docs)
- Emit good error messages for mismatched parentheses
=> Improve self-hosted tokenizer

self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, src/typecheck.c, tests/other_errors/using_void_function.jou, tests/other_errors/using_void_method.jou
There was already a nice error message for functions. I changed it to do the same thing for methods.
=> Fix compiler crash when trying to use the return value of a '-> void' method

.github/workflows/windows.yml, runtests.sh
I changed how Windows builds work in #293, and the generated `.zip` files are no longer tested: if they don't work for whatever reason, I probably wouldn't notice it until a user complains. This PR adds a test to improve the situation.
=> Test the produced zip files in GitHub Actions

.github/workflows/windows.yml
This relatively simple step in the build on GitHub Actions currently takes 3min 30sec. Hopefully it is faster with this PR.
=> Speed up copying DLLs

src/build_cfg.c, src/codegen.c, src/free.c, src/jou_compiler.h, src/main.c, src/typecheck.c, tests/other_errors/imported_error.jou
Previously the last stage of typechecking was called as a part of building the CFG of a function or method. This was just a weird design with no real advantages. This PR changes the compiler to typecheck all functions before any CFGs are built, like you would expect it to do.
=> Get rid of reset_type_context()

runtests.sh
Since #240 one test has failed if you run `./runtests.sh`. Not caught in github actions, because the bug didn't occur if you pass in an optimize flag explicitly like github does (only the default was changed in #240)
=> Fix running ./runtests.sh locally

compare_compilers.sh, self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt
- Fix CRLF problems on Linux (and on Windows, if your git config doesn't have autocrlf enabled)
- Complain if error list files mention nonexistent files (also works with `--fix`)
- Move `set -e` where it belongs, so that errors in argument handling will not be ignored
=> compare_compilers.sh improvements

compare_compilers.sh, self_hosted/ast.jou, self_hosted/create_llvm_ir.jou, self_hosted/parser.jou, self_hosted/runs_wrong.txt, self_hosted/typecheck.jou, src/build_cfg.c, src/free.c, src/jou_compiler.h, src/main.c, src/parse.c, src/print.c, src/typecheck.c
E.g. function declarations and function definitions now use the same data structure, and are distinguished by whether the body is empty.
This seems a bit weird at first, but IMO results in less copy/pasta and more readable code.
=> Small code cleanup: combine related things

.github/workflows/linux.yml, compare_compilers.sh, runtests.sh
There are many bash scripts :)
There's a lot of excludes in the shellcheck command, because in this repo I prefer to *not* handle whitespaces in file paths properly. All paths are relative to the repository, and the repository itself doesn't contain file paths with spaces, for example.
Also fixes the CRLF detection bug mentioned in #322. I originally discovered it without shellcheck though.
=> Add shellcheck

src/codegen.c
~Similar to how clang works, at least according to https://stackoverflow.com/a/12757239~
The previous solution of just using i8 array won't work on platforms that need stuff to be aligned. On x86_64 you don't need to align things, so that's why it worked, but it could cause problems if I port Jou to a different platform.
I changed it to array of i64 (of appropriate size), so it is always aligned as needed. It can be larger than necessary though, if your union is very small otherwise.
=> Change union codegen to be aligned properly

Makefile.posix, Makefile.windows, src/main.c
After #327 the self-hosted compiler compiles in just a few seconds, so the main purpose of `-v` is for someone new to the compiler to learn how it works (see CONTRIBUTING.md). I changed it to print one line for each compilation step (e.g. `Tokenizing /home/akuli/jou/stdlib/_assert_fail.jou`) instead of vaguely combining multiple steps into one (e.g. `Parsing Jou files...`)
=> Print a little bit more with -v/--verbose

self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, src/typecheck.c, tests/other_errors/field_of_a_field_of_a_field_error.jou, tests/other_errors/function_call_indexing.jou, tests/other_errors/immediate_member_assign.jou, tests/other_errors/increment_indirect_addressof_fails.jou, tests/other_errors/instantiation_address_of_field.jou
The purpose of `ensure_can_take_address()` is to check that making a pointer to something (as in `&foo`) makes sense. But unlike you would expect, it isn't used just in the `&foo` syntax. Several other things, such as `foo = bar` and `&foo.bar`, also need a pointer to `foo`. The `ensure_can_take_address()` function handles them all.
This means that it is important for `ensure_can_take_address()` to generate good error messages. The error message logic is also a bit complicated, and previously behaved wrong in some corner cases: `Foo{}.x++` resulted in an error message saying you are trying to increment a newly created instance. It now says that you are trying to increment a *field* of a newly created instance.
=> Improve ensure_can_take_address

self_hosted/parser.jou, src/build_cfg.c, src/codegen.c, src/jou_compiler.h, src/print.c, src/tokenize.c, src/typecheck.c, tests/should_succeed/pointer.jou
E.g. `&foo[0] < &foo[1]`. Fixes #279
=> Pointer comparisons

src/codegen.c, tests/should_succeed/global.jou
There is already code that relies on this, although previously LLVM didn't guarantee it.
=> Initialize global variables to zero

self_hosted/runs_wrong.txt, stdlib/ascii.jou, stdlib/io.jou, stdlib/str.jou
Used these to solve day 2 and 3 of advent of code 2023.
So far I have solved all 3 AOC problems with Jou. I'm planning to put my solutions to `examples/` folder and add them to tests once this PR is merged.
=> Add Advent of Code related functions

.github/workflows/linux.yml, runtests.sh
When I modified `runtests.sh`, valgrind didn't run, so I broke valgrinding by specifying a wrong relative path. This PR fixes the valgrinding, and also runs it for more PRs so this shouldn't happen again.
=> Fix valgrinding

self_hosted/parser.jou, src/parse.c, tests/other_errors/python_init_method.jou
=> add error for __init__ method

tests/should_succeed/ascii_test.jou
=> Add tests for split_by_ascii_whitespace

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, CONTRIBUTING.md, doc/perf.md, doctest.sh
=> Add tests for docs

examples/aoc2023/day05/part2.jou, self_hosted/runs_wrong.txt, src/simplify_cfg.c, tests/should_succeed/and_or_not.jou, tests/should_succeed/unused_import.jou, tests/should_succeed/unused_variable.jou
Fixes #422 
Turns out this warning never existed. I created it now.
=> Add unused variable warning

src/output.c, src/run.c
Will be a tiny file, but doesn't make sense to have it in `output.c`.
For now this isn't needed on the self-hosted side, because it has running in `main.jou`
=> move run_exe() to separate file

self_hosted/typecheck.jou, src/codegen.c, src/typecheck.c
A simpler fix to #48 than what I wrote originally.
Extracted from #454
=> Cast array indexes to long

src/main.c, tests/should_succeed/compiler_cli.jou
fix #463
I am sorry I forgot to change that
=> O1 is the default in the help message

doc/tutorial.md, self_hosted/create_llvm_ir.jou, self_hosted/llvm.jou, self_hosted/typecheck.jou, src/build_cfg.c, src/codegen.c, src/jou_compiler.h, src/print.c, src/typecheck.c, tests/should_succeed/cast_between_ptr_and_long.jou, tests/wrong_type/pointer_to_int.jou
=> Add casts: pointer <--> long

tests/wrong_type/deref_array.jou
In Jou (unlike in C), you are supposed to use the `*` operator only with pointers, not with arrays. This already works as expected, but there wasn't a test.
=> Add test for *array

examples/aoc2023/day24/bigint.jou, src/typecheck.c, tests/should_succeed/method_by_value.jou
=> Allow taking address of self when it is passed by value

self_hosted/create_llvm_ir.jou, self_hosted/typecheck.jou, src/build_cfg.c, src/typecheck.c, tests/should_succeed/bool_eq_bool.jou, tests/wrong_type/bool_plus_bool.jou
=> Add == for booleans

src/simplify_cfg.c, tests/other_errors/assert_fail.jou, tests/other_errors/assert_fail_multiline.jou, tests/should_succeed/and_or_not.jou, tests/should_succeed/unreachable_warning.jou
=> Handle CF_BOOL_NEGATE in simplify_cfg

doc/tutorial.md
=> Explain more pointer stuff in tutorial

examples/aoc2023/day07/part1.jou, examples/aoc2023/day07/part2.jou, examples/aoc2023/day08/part2.jou, examples/aoc2023/day09/part2.jou, examples/aoc2023/day20/part2.jou, examples/aoc2024/day01/part1.jou, examples/aoc2024/day05/part2.jou, examples/quicksort.jou, stdlib/mem.jou, tests/should_succeed/memlibtest.jou
This function swaps the contents of two chunks of memory. It is intended to be used whenever you want to swap two variables.
~I also documented the rest of `mem.jou` slightly better.~ #529
=> Add `memswap()` function to stdlib/mem.jou

doc/tutorial.md, examples/aoc2023/day03/part2.jou, examples/aoc2023/day05/part1.jou, examples/aoc2023/day05/part2.jou, examples/aoc2023/day24/part1.jou, examples/aoc2023/day24/part2.jou, examples/aoc2024/day01/part1.jou, examples/aoc2024/day13/part1.jou, examples/aoc2024/day13/part2.jou, examples/aoc2024/day14/part1.jou, examples/aoc2024/day14/part2.jou, examples/aoc2024/day18/part2.jou, self_hosted/parser.jou, self_hosted/parses_wrong.txt, self_hosted/runs_wrong.txt, src/parse.c, tests/should_succeed/sscanf.jou, tests/syntax_error/double_assignment_comma_typed.jou, tests/syntax_error/double_assignment_comma_untyped.jou, tests/syntax_error/local_var_comma.jou, tests/syntax_error/local_vars_comma.jou, tests/syntax_error/local_vars_comma_assign.jou, tests/syntax_error/python_style_unpack.jou
Limitations:
- Initial value cannot be set: `x, y: int = 0` is an error. This is by design, because `x, y = foo` looks like Python's unpacking. (Jou doesn't have unpacking.)
- Only works for local variables, not for e.g. globals, class fields (could be useful), function parameters.
Fixes #536
=> Allow `x, y: int` syntax for declaring local variables

self_hosted/typecheck.jou, src/typecheck.c, tests/should_succeed/array_to_voidptr.jou
=> Add array to void* implicit cast

.github/workflows/linux.yml, .github/workflows/valgrind.yml
Running tests with valgrind is by far the slowest thing in CI when making a pull request. Let's stop doing that.
See also: #551
=> Configure GitHub Actions to run tests with valgrind every night instead of every pull request

.github/workflows/valgrind.yml, runtests.sh
- Last night, valgrind ran out of memory. Do not enable memory limit when running valgrind, because it consumes more memory than the program by itself, and seems to be somewhat unpredictable.
- If one valgrind run fails, do not immediately stop the others. It can be useful to know which runs fail, e.g. if only one of them fails, it is probably random/undeterministic and doesn't fail every time.
Fixes #557
=> Fix valgrind

src/codegen.c
I could no longer understand what the code does by looking at it, so I rewrote it in a much simpler way using an LLM.
=> Compiler: Simplify codegen of arithmetic operations

.github/workflows/autofix.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/netbsd.yml, .github/workflows/release.yml, .github/workflows/valgrind.yml, .github/workflows/windows.yml
This is a best practice that I forgot to do. I noticed this when I somehow managed to freeze the netbsd build in #562.
=> Add timeouts to all GitHub Actions workflows

.github/workflows/valgrind.yml
- Rewrite in bash, so that it can be tested locally unlike github-flavored javascript
- Do not create another issue if an open issue about this already exists, so that I don't get spammed daily if I don't fix valgrind for whatever reason
=> Improve the valgrind workflow

bootstrap_compiler/typecheck.c, compiler/build_cfg.jou, compiler/typecheck.jou, examples/aoc2024/day21/part2.jou, tests/should_succeed/array.jou, tests/wrong_type/array_mixed_types_ptr.jou
=> Fix arrays of strings and NULLs

bootstrap_compiler/build_cfg.c, bootstrap_compiler/free.c, bootstrap_compiler/jou_compiler.h, bootstrap_compiler/typecheck.c, compiler/ast.jou, compiler/build_cf_graph.jou, compiler/main.jou, compiler/typecheck/common.jou, compiler/typecheck/step3_function_and_method_bodies.jou
**Old approach:** During type checking, we build an array of `ExpressionTypes`, which holds the types of each expression in the function. Each `ExpressionTypes` has a pointer to the corresponding `AstExpression`.
**New approach:** `AstExpression` contains `ExpressionTypes`. It is filled in during type checking.
New approach is simpler. I thought about it when I chose to use the old approach, but my OOP-poisoned brain thought it is somehow worse. It isn't.
I also updated (somewhat lazily) the bootstrap compiler.
=> Compiler refactor: put ExpressionTypes inside AstExpression

README.md, doc/classes.md, doctest.sh
=> Document classes

bootstrap_compiler/typecheck.c, compiler/ast.jou, compiler/typecheck/step3_function_and_method_bodies.jou, tests/404/enum.jou, tests/404/enum_member.jou, tests/already_exists_error/enum.jou, tests/other_errors/assign_to_enum.jou, tests/other_errors/enum_arrow.jou, tests/should_succeed/enum.jou, tests/should_succeed/enum_and_local_var.jou, tests/should_succeed/local_import.jou, tests/wrong_type/enum_member_from_class.jou, tests/wrong_type/int_to_enum.jou, tests/wrong_type/using_class_like_enum.jou
Part 1/3 of #599 
Closes #357 
There will temporarily be two enum syntaxes: `::` and `.` will both work. The `::` syntax will go away soon.
=> Add `.` syntax for enums

bootstrap_compiler/typecheck.c, compiler/ast.jou, compiler/build_cf_graph.jou, compiler/parser.jou, compiler/tokenizer.jou, compiler/typecheck/step3_function_and_method_bodies.jou
=> Fix memory leaks

bootstrap_compiler/run.c
Fixes #525 
There are also various deprecation warnings now (#365)
=> Fix C compiler warning in bootstrap compiler

bootstrap_compiler/parse.c, compiler/parser.jou, tests/should_succeed/match.jou, tests/syntax_error/match_bad_case_parens.jou
Example:
```python
match foo:
case (
Foo.Bar1
| Foo.Bar2
| Foo.Bar3
| Foo.Bar4
| Foo.Bar5
):
printf("yea\n")
case _:
printf("nope\n")
```
=> Allow parentheses in match cases

bootstrap_compiler/codegen.c, compiler/codegen.jou
This is a leftover from #614 that is no longer needed.
=> Compilers: clean up pointer handling in codegen

compiler/typecheck/step3_function_and_method_bodies.jou, tests/wrong_type/enum_as_vararg.jou
=> Ban enums as variadic arguments

compiler/constants.jou, compiler/typecheck/step3_function_and_method_bodies.jou, tests/wrong_type/enums_mix_eq.jou
=> Ban comparing enums of different types

.github/workflows/checks.yml, .github/workflows/linux.yml
Checks in the new file `checks.yml` run on linux, but that's not really the point of the checks. They don't test whether Jou works on linux, they check various other things.
=> GitHub Actions: split some of linux.yml into new file checks.yml

.github/workflows/valgrind.yml
All other github actions files already use `runs-on: ubuntu-latest`.
Fixes #640
=> Use ubuntu-latest for running valgrind

.github/workflows/valgrind.yml
- Build a list of failed valgrind runs instead of showing only the first one.
- Refactor the code to use bash functions, so that it's easier to test it locally. You still need to substitute various `${{ github.foo }}` values with find/replace when testing.
=> Valgrind github config improvements

compiler/build_cf_graph.jou, compiler/parser.jou
Error for `break` or `continue` outside loop is now done during parsing. Maybe some day, @taahol will extend this to handle #362 :)
There was also another error that never actually happened, because typecheck already handles that error case.
=> compiler refactor: Move error messages out of build_cfg

bootstrap_compiler/build_llvm_ir.c, bootstrap_compiler/jou_compiler.h, bootstrap_compiler/typecheck.c, compiler/ast.jou, compiler/build_cf_graph.jou, compiler/typecheck/step3_function_and_method_bodies.jou
=> both compilers: Improve naming of fields in ExpressionTypes

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml
The CI sometimes fails because it goes a few seconds over 5 minutes for whatever reason. Let's give it some "breathing room".
=> GitHub Actions: bump test timeouts to 10 minutes

examples/aoc2023/day19/part2.jou
Apparently there's no way to specifically disable `realloc(ptr, 0)` warnings in valgrind, so let's work around them instead.
Fixes #654
=> Avoid realloc(ptr, 0) to satisfy valgrind

compiler/typecheck/step3_function_and_method_bodies.jou, tests/wrong_type/assert.jou, tests/wrong_type/elif.jou, tests/wrong_type/for.jou, tests/wrong_type/if.jou, tests/wrong_type/not.jou, tests/wrong_type/or.jou, tests/wrong_type/while.jou
Today @taahol ran into this. He tried converting a value to type `boolean`, which doesn't exist because it's `bool`, so let's just say `bool` in error messages.
=> Typecheck error messages: boolean --> bool

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml
For two reasons:
- may catch subtle bugs that only appear when compiling something large
- fun
=> When making pull request, compile the compiler with itself

Makefile.posix, Makefile.windows
This way you will not end up with an outdated bootstrapped compiler while working on Jou. If it needs to be bootstrapped again, it will be bootstrapped again.
=> Re-run bootstrap.sh if it changes

.github/workflows/checks.yml, check-markdown-links.py
Sometimes the CI fails because a link is temporarily down. To work around this, try each link 5 times if it doesn't work.
=> Add retrying to link checker

compiler/ast.jou, compiler/build_cf_graph.jou, compiler/typecheck/step3_function_and_method_bodies.jou
Much simpler than finding it again later.
The compiler is full of little refactor possibilities like this. CFG (Control Flow Graph) related things are the messiest, but fortunately I will soon replace them with a different approach to analyzing the code and building LLVM IR.
=> Compiler refactor: store called function signature to AstCall

compiler/ast.jou, compiler/builders/ast_to_builder.jou, compiler/parser.jou, compiler/tokenizer.jou, compiler/typecheck/step3_function_and_method_bodies.jou, doc/syntax-spec.md, tests/404/match_function.jou, tests/should_succeed/match.jou, tests/syntax_error/match_bad_with.jou, tests/wrong_type/match_function_num_args.jou, tests/wrong_type/match_function_return_type.jou, tests/wrong_type/match_function_varargs.jou, tests/wrong_type/match_with_arg1.jou, tests/wrong_type/match_with_arg2.jou
Fixes #617
Example:
```python
match "hello" with strcmp:
case "hello":
printf("yass\n")
```
For now, the match function must return `int`, so you can't match with e.g. `starts_with()`. This might actually be a good thing, so that usage of `match` statement remains quite simple and it's not tempting to make things more complicated than needed.
=> Add "match ... with ..." syntax

bootstrap.sh, compiler/command_line_args.jou, compiler/evaluate.jou, compiler/tokenizer.jou, compiler/typecheck/common.jou, examples/aoc2023/day02/part2.jou, examples/aoc2023/day19/part1.jou, examples/aoc2024/day24/part1.jou, examples/aoc2024/day24/part2.jou
The code is slightly longer, but much more readable.
Currently `match some_byte:` doesn't work, but `match some_byte with bytecmp` does, where `bytecmp` is the following function:
```python
def bytecmp(a: byte, b: byte) -> int:
return (a as int) - (b as int)
```
=> Use "match ... with ..." statements in compiler and examples

bootstrap.sh
This is good from a security point of view. It prevents the following attack:
- Attacker can somehow push malicious code into my repository `Akuli/jou`, but not onto the main branch
- Attacker pretends to be a contributor who needs to add another Git revision to the bootstrap script
- Attacker adds malicious commit hash to bootstrap script
Without this PR, bootstrap script would happily compile with the malicious commit hash. With this PR, the bootstrap script will notice that the commit hash is not on the `main` branch and stop.
The attack is very unlikely, but this sanity check cannot be a bad thing, so might as well add it.
=> bootstrap.sh: Add commit hash sanity check

bootstrap.sh, compiler/paths.jou, stdlib/errno.jou
=> Use compile time if statements

bootstrap.sh
- Save all bootstrapped compilers. Commit hash is included in folder name, so that this will work even if commits are removed from the list (unlikely).
- When a new commit is added to the bootstrap process, don't recompile everything from scratch.
- ~~For the first commit, use the compiler written in C directly instead of compiling a compiler written in Jou with it.~~ (failed on Windows for some reason)
Fixes #711
=> Bootstrap script improvements

compiler/builders/ast_to_builder.jou, compiler/typecheck/step3_function_and_method_bodies.jou, compiler/types_in_ast.jou, tests/should_succeed/array.jou, tests/should_succeed/sizeof.jou
Sounds fancy, but it isn't. It just means that when we are type-checking an expression, we have some idea about what we expect the resulting type to be.
For example, if you do `foo: byte[100] = "hello"`, when we type-check the string `"hello"`, the type of the string becomes `byte[100]`. But if you do `foo = "hello"` without specifying a type, the type of the string becomes `byte*`.
Fixes #683
=> Determine type of strings with bidirectional type inference

bootstrap.sh, compiler/builders/ast_to_builder.jou
Uses the stuff implemented in #714. Must be separate PR because #714 must be added to bootstrap script.
=> Compiler code cleanup: simplify array of strings

.github/workflows/linux.yml, Makefile.posix, Makefile.windows
Currently folder paths in `Makefile.*` and `bootstrap.sh` are not the same like they should be, which causes `make clean` to print a lot of unnecessary output.
=> Fix 'make clean'

.github/workflows/valgrind.yml
No need to run it every night, since we're not going to create an issue anyway. It can still be triggered manually.
=> Prevent valgrind from running on forks

compiler/builders/ast_to_builder.jou, compiler/typecheck/step3_function_and_method_bodies.jou, doc/enums.md, tests/other_errors/match_enum_too_dynamic.jou, tests/should_succeed/match.jou
Two things.
This is no longer valid:
```python
enum Thingy:
Foo
Bar
Baz
def get_bar() -> Thingy:
return Thingy.Bar
def do_stuff(t: Thingy) -> None:
match t:
case get_bar():  # error on this line
...
```
When matching over enums, cases must be simple `EnumName.MemberName`, nothing more complicated is allowed.
After this PR, the following function will invoke UB if you do `thingy_to_string(7 as Thingy)`:
```python
enum Thingy:
Foo
Bar
Baz
def thingy_to_string(t: Thingy) -> byte*:
match t:
case Thingy.Foo:
return "It's a foo"
case Thingy.Bar:
return "Barbar"
case Thingy.Baz:
return "Bazzz"
```
Currently the match statement does nothing, which means that the compiler should complain about how the function might not return a value. It doesn't because undefined value checks are currently …
=> Changes to how match statements interact with enums

release.sh
I created #731 just so I could label it with `skip-release` and avoid showing it in release descriptions. I don't want to do that.
=> Do not mention non-PR commits in release descriptions

tests/should_succeed/assert_success.jou
Currently there is no warning for `assert True`. Let's ensure it stays that way.
Closes #480
=> Add tests for assert True

compiler/tokenizer.jou, doc/compiler_internals/syntax-spec.md, tests/should_succeed/unicode_varname.jou, tests/syntax_error/no_break_space.jou
For now, we allow all non-ASCII characters except whitespace characters. In the future, we could e.g. include a big list of allowed characters into the executable with #607.
Fixes #71
=> Allow non-ASCII variable names

compiler/ast.jou, compiler/builders/ast_to_builder.jou, compiler/builders/llvm_builder.jou, compiler/command_line_args.jou, compiler/main.jou, compiler/parser.jou, compiler/target.jou, compiler/typecheck/step2_populate_types.jou, compiler/typecheck/step3_function_and_method_bodies.jou, compiler/types.jou, compiler/types_in_ast.jou, stdlib/_jou_startup.jou, tests/other_errors/import_private_global_var.jou, tests/other_errors/imported/privates.jou, tests/should_succeed/imported/bar.jou, tests/should_succeed/imported/samename1.jou, tests/should_succeed/imported/samename2.jou, tests/should_succeed/local_import.jou, tests/should_succeed/unused_global.jou
You can use `@public` to make a global variable accessible from other files (just like functions):
```python
@public
global foo: int
```
Without `global`, the variable is private to the file (known as `static` in C and similar languages). Other files cannot access it directly even if they import the file.
Part of #84
=> Make global variable definitions private by default

.github/workflows/checks.yml
Theorethically, `editorconfig-checker` people could upload a malicious release of `editorconfig-checker` with the same version number, and Jou's CI setup would pick it up. This prevents that. It is a very unlikely attack, but adding a checksum doesn't matter either.
Most other downloaded things already use checksums. See e.g. `windows_setup.sh`.
=> GitHub Actions: Verify checksum of editorconfig

compiler/ast.jou, compiler/main.jou, compiler/parser.jou, compiler/typecheck/step2_populate_types.jou, stdlib/io.jou, tests/other_errors/import_private_global_var_declare.jou, tests/other_errors/imported/privates.jou, tests/should_succeed/imported/samename1.jou, tests/should_succeed/imported/samename2.jou, tests/should_succeed/same_name_functions_not_public.jou, tests/should_succeed/unused_global.jou
Same as #751 but for the `declare global` syntax. Part of #84.
=> Make global variable declarations private by default

compiler/ast.jou, compiler/builders/either_builder.jou, compiler/builders/llvm_builder.jou, compiler/builders/uvg_builder.jou, compiler/errors_and_warnings.jou, compiler/llvm.jou, compiler/main.jou, compiler/parser.jou, compiler/token.jou, compiler/typecheck/common.jou, compiler/typecheck/step1_create_types.jou, compiler/types.jou, compiler/types_in_ast.jou, compiler/uvg.jou, doc/imports.md, examples/aoc2023/day24/bigint.jou, examples/aoc2023/grid.jou, stdlib/io.jou, tests/other_errors/import_private_class.jou, tests/other_errors/imported/privates.jou, tests/other_errors/public_method.jou, tests/should_succeed/imported/bar.jou, tests/should_succeed/unused_class.jou
Example:
```python
class PrivateClass:
...
@public
class PublicClass:
...
```
For now, all methods are considered public, and there's no warning for unused methods. This turned out to be more difficult to implement than I thought. I created #758.
Closes #84
=> Make classes private by default

compiler/main.jou, compiler/parser.jou, compiler/typecheck/step2_populate_types.jou, examples/x11_window.jou, stdlib/io.jou, tests/should_succeed/empty_class.jou, tests/should_succeed/pass.jou, tests/wrong_place/pass_outside_function.jou
Fixes #707 
Does not change compiler or stdlib yet, because that would break bootstrapping: older compiler must be able to compile latest compiler with latest stdlib.
=> Allow empty class

compiler/evaluate.jou, tests/should_succeed/compile_time_if.jou
Needed for #763 
Previously, compile-time evaluatable if statements inside runtime if statements were never evaluated.
For example, if you don't use windows, the following would procude a compiler warning even though the code would run on Windows:
```python
if some_dynamic_thing() == other_dynamic_thing():
if WINDOWS:
do_stuff()  # Warning: this code will never run
```
This PR removes the warning, because it evalutes `if WINDOWS:` at compile time before we do the warnings.
=> Fix a corner case in compile-time if statement handling

compiler/paths.jou
@taahol explained to me that on NetBSD, invoking `stat()` in C actually calls a function named `__stat50()`. There is also a function whose name is actually `stat()`, and it's some legacy thing that produces a linker warning if you try to use it.
Jou is currently using the legacy `stat()`. Let's not use `stat()` at all in the compiler, because we can still avoid it.
I don't know yet what I want to do if I some day add a `stat()` to the Jou standard library.
=> Fix stat() linker warning on NetBSD

compiler/ast.jou, compiler/builders/ast_to_builder.jou, compiler/evaluate.jou, compiler/parser.jou, compiler/typecheck/step3_function_and_method_bodies.jou
#797 added support for compile-time constants. To do that, it introduced `AstExpressionType.Constant`, which represent an expression whose value is known at compile time.
This PR refactors the compiler to also use `AstExpressionType.Constant` for integer literals (e.g. `123`), `True`/`False` and a few other things.
=> Compiler refactor: use AstExpressionKind.Constant for literals

bootstrap.sh, compiler/tokenizer.jou, examples/aoc2024/day03/part1.jou, examples/aoc2024/day03/part2.jou, examples/aoc2024/day15/part1.jou, examples/aoc2024/day15/part2.jou, stdlib/io.jou, tests/should_succeed/file.jou
`getchar()` and `fgets()` return the constant `EOF` when reading fails or end of file occurs. EOF is `-1` on all platforms that Jou currently supports, so in the past, the number `-1` has been hard-coded every time EOF was needed.
I also documented how EOF constant is meant to be used.
=> Add EOF constant to stdlib/io.jou

compiler/builders/llvm_builder.jou, compiler/typecheck/step1_create_types.jou, compiler/typecheck/step2_populate_types.jou, compiler/types.jou
This was useless. It felt like a good idea when it was added but it really serves no purpose.
=> Compiler code cleanup: delete TypeKind.OpaqueClass

examples/list_example.jou, stdlib/list.jou
Generic `List[T]` is finally here!
A caveat is that instead of `list.append(foo)`, you need `list.append(&foo, sizeof(foo))` due to how generics work in Jou. This will be fixed later when we have inline functions. See also #805.
On another branch, I have already converted the Jou compiler to use the new `List`. I will make a separate pull request for that.
=> Add generic List class to stdlib

compiler/typecheck/common.jou, compiler/types.jou, tests/should_succeed/generic_bug_with_substituting_T_to_T.jou
Fixes #814 
The problem was that when replacing `T` with `T` in `Foo[T]`, we created a new type named `Foo[T]` instead of reusing the same one.
=> Fix compiler crash when generic class references itself

bootstrap.sh, compiler/constants.jou, compiler/typecheck/step3_function_and_method_bodies.jou, compiler/types.jou, stdlib/list.jou, tests/should_succeed/list_test.jou
Use `list.extend(other_list)` to append all items from another list.
Use `list.extend_from_ptr(ptr, 3, sizeof(ptr[0]))` to append `ptr[0]`, `ptr[1]` and `ptr[2]` to the list.
=> Add extend() and extend_from_ptr() methods to List

compiler/typecheck/step3_function_and_method_bodies.jou
When doing `foo: byte[10] = "hi"` or similar, the string `"hi"` turns from a pointer string constant into an array string constant. Since #813 (PR that introduced this bug), pointer string constants are internally `byte*` and array string constants are `List[byte]`. This PR frees the `byte*` string after constructing the corresponding `List[byte]`.
Fixes #819
=> Fix memory leak in compiler

doc/compiler_internals/syntax-spec.md
This is exactly what any programmer would expect, but I noticed it wasn't documented.
=> Document double backslash inside string/byte literals

.github/workflows/macos.yml
Fixes #833 
The cached bootstrap compiler stopped working for some reason. There's no need to cache it at all. MacOS tests are not ran every time someone makes a pull request, so they don't need to be particularly fast.
=> Do not cache bootstrap compiler on macos

.github/workflows/checks.yml, doc/compiler_internals/architecture-and-design.md
Jou code in markdown files uses "Python" syntax highlighting. GitHub supports multiple ways of specifying it, at least the following:
```python
```python3
```py
```py3
`doctest.sh` only supports the `python` marker. This PR adds a check to CI that fails if any of the other markers are used.
=> Fail CI if using ```python3 accidentally

.github/workflows/windows.yml
Once these are added, Jou releases contain everything you need to compile code that uses LLVM. This means that `./windows_setup.sh --small` will no longer need to download a sketchy `mingw64_small.zip` created manually by me.
The release zips will be slightly bigger after this change. We'll see how much bigger.
**Edit:** Size increase is 44M --> 46M. Not bad at all.
=> Add LLVM `.a` files to Jou releases

.github/workflows/windows.yml
The empty `jou/lib` folder was caused by messy code, so I rewrote it. It still copies the same exact files, but much simpler, and creates directories as needed.
Fixes #853
=> Windows build: simplify file copying logic

.github/workflows/windows.yml
Similarly to #852, this is needed to get rid of `akuli.github.io/mingw64-small.zip`, but this will make the Jou release zip files slightly bigger.
=> Windows build: include mingw32-make.exe

.github/workflows/windows.yml, compiler/llvm.jou
**This PR breaks `windows_setup.sh --small` temporarily. I will fix it in my next PR.**
Since #852, content of "libs" folder is available directly inside the `mingw64` folder. I will soon get rid of the `libs` folder in a separate PR.
=> Windows: do not use "libs" folder

check-markdown-links.py
For two reasons:
1. It is good if website owners can look at their server logs to figure out why I'm doing these requests, and contact me if they want me to stop
2. The default user-agent `python-requests/x.y.z` (x.y.z = version number) is often banned, e.g. advent of code
=> Add User-Agent header to check-markdown-links.py

compiler/typecheck/common.jou, compiler/types.jou, doc/types.md, tests/should_succeed/fixed_size_types.jou, tests/should_succeed/sizeof.jou, tests/wrong_type/uint16_instead_of_byte.jou
Adds 8 new types to the Jou language:
- `int8`
- `uint8` (same as `byte`)
- `int16` (same as `short`)
- `uint16` 
- `int32` (same as `int`)
- `uint32`
- `int64` (same as `long`)
- `uint64`
Fixes #164
=> Add fixed-size integer types

Makefile.posix, Makefile.windows
Basically applies #847 to developing the Jou compiler. Recompiling after a simple change now takes 1 second instead of 8 seconds.
=> When developing Jou compiler, don't recompile from scratch every time

compiler/parser.jou, compiler/tokenizer.jou, compiler/typecheck/common.jou, compiler/types.jou, doc/compiler_internals/syntax-spec.md, doc/types.md, tests/should_succeed/printf.jou
Use `int16` instead of `short`. It does the same thing but the name is more explicit.
Also, `short` was never really used anywhere. The main use case I can think of is audio: a typical `.wav` file is a few headers and a big list of 16-bit integers. I haven't done much audio stuff with Jou.
Related to #515
=> Delete the `short` data type

bootstrap.sh, compiler/hash.jou, compiler/uvg_analyze.jou
Recompiling the Jou compiler with no changes done to it is now about ~~40%~~ 45% faster. On my ancient laptop, it took 2.8 seconds before and it's now ~~1.7~~ 1.55 seconds.
<details>
<summary>Script used to measure performance</summary>
```
#!/bin/bash
set -ex
make
./jou -o jou2 compiler/main.jou
#valgrind --tool=callgrind ./jou -v -o jou2 compiler/main.jou
(
for i in $(seq 5); do time ./jou -o jou2 compiler/main.jou; done
) 2>&1 | tr , . | python3 -c '
import re, sys
data = re.findall(r"real\s+0m(.*)s", sys.stdin.read())
print(sum(map(float, data)) / len(data))
'
```
</details>
=> Make the Jou compiler faster

.github/workflows/checks.yml, .gitignore, check-markdown-links.py
- Do not complain if a link has been down for less than 3 days.
- Delete the retrying logic. It is no longer needed.
- Use a hard-coded/pinned version of Python's `requests` library. This is better for security (although `requests` is very unlikely to get hacked) and makes the check less likely to break by itself.
=> Improve markdown link checker

bootstrap.sh, compiler/uvg_analyze.jou
Seems like a slightly nicer way to do the thing.
=> Compiler code cleanup: use bitflags for UVG statuses

compiler/main.jou, compiler/parser.jou, compiler/typecheck/step2_populate_types.jou, compiler/typecheck/step3_function_and_method_bodies.jou, tests/other_errors/assert_cannot_compile_time_evaluate.jou, tests/other_errors/assert_fail_compile_time.jou, tests/should_succeed/assert_success.jou, tests/wrong_place/assert_in_class_body.jou, tests/wrong_place/assert_outside_function.jou, tests/wrong_type/assert_compile_time.jou
It is now possible to write `assert not WINDOWS` outside a function. This way, you can avoid accidentally importing a Windows-specific module on Linux, for example.
Before it produced the following error:
```
compiler error in file "a.jou", line 1: 'assert' must be inside a function or method
```
This is similar to `static_assert` in C/C++.
Fixes #882.
=> Add compile-time asserts

compiler/ast.jou, compiler/builders/ast_to_builder.jou, compiler/parser.jou, compiler/typecheck/step3_function_and_method_bodies.jou, doc/classes.md, doc/lists.md, tests/other_errors/enum_arrow.jou, tests/wrong_type/arrow_instead_of_dot.jou, tests/wrong_type/arrow_instead_of_dot_call.jou, tests/wrong_type/arrow_operator_int.jou, tests/wrong_type/arrow_operator_int_call.jou, tests/wrong_type/arrow_operator_intptr.jou, tests/wrong_type/arrow_operator_intptr_call.jou, tests/wrong_type/dot_instead_of_arrow.jou, tests/wrong_type/dot_instead_of_arrow_call.jou, tests/wrong_type/dot_operator_int.jou, tests/wrong_type/dot_operator_int_call.jou, tests/wrong_type/dot_operator_intptr.jou, tests/wrong_type/dot_operator_intptr_call.jou
Example:
```python
import "stdlib/io.jou"
class Foo:
x: int
def move(f: Foo*) -> None:
#f->x++  # old syntax
f.x++
```
Before this PR, there were two ways to access attributes: `foo.bar` and `foo->bar`. You used `foo.bar` if `foo` is an instance and `foo->bar` if `foo` is a pointer to an instance.
This PR modifies `.` to work for both use cases. For backwards compatibility, `foo->bar` will do the same thing as `foo.bar` for a few hours. Then I will remove the `foo->bar` syntax.
Todo:
Part of #749
=> Allow using `.` instead of `->` to look up members from pointers

compiler/ast.jou, compiler/builders/any_builder.jou, compiler/builders/hash_builder.jou, compiler/builders/llvm_builder.jou, compiler/evaluate.jou, compiler/parser.jou, examples/aoc2023/day19/part2.jou, examples/aoc2023/day20/part1.jou, examples/aoc2023/day23/part2.jou, examples/aoc2023/day24/part1.jou, examples/aoc2023/day24/part2.jou, tests/should_succeed/method_by_value.jou, tests/syntax_error/arrow_field.jou, tests/syntax_error/arrow_method.jou
Turns out that `->` support was already broken since #902. This PR adds a nice error message if you try to use `->`.
Fixes #749
=> Remove support for `foo->bar` syntax

examples/perlin_noise.jou, stdlib/math.jou, tests/should_succeed/mathlibtest.jou
- Add `M_PI` (3.1415...) and `M_E` (2.71828...) constants.
- Delete functions that don't exist on NetBSD: `exp10`, `exp10f`
- Delete functions that nobody uses: `erfc`, `erfcf`, `tgamma`, `tgammaf`, `lgamma`, `lgammaf`
- Improve documentation comments.
- Rearrange functions (e.g. `sin` before `cos`) to make the file more readable.
=> Improve stdlib/math.jou

compiler/main.jou, tests/should_succeed/compiler_cli.jou
This is a small technical thing that doesn't affect using Jou.
Nowadays `stdlib/_jou_startup.jou` is used for nothing. Before #910 it was used to set up global `stdin`, `stdout` and `stderr` variables, but they no longer exist.
We can delete `stdlib/_jou_startup.jou` when the bootstrap compiler has been updated to a version that doesn't require it.
=> Do not implicitly compile with stdlib/_jou_startup.jou

.github/workflows/checks.yml, .github/workflows/linux.yml, .github/workflows/valgrind.yml
Sometimes `sudo apt update` is needed to avoid weird apt errors in `sudo apt install`. This PR changes the 11 Linux CI jobs to first try without it, and if that fails, run `sudo apt install` and try again.
=> CI: avoid `apt update` if `apt install` works without it
